name: CBAA NAD
favicon: null
layout_spectrum: 0.03772660670801997
typography_spectrum: 0.3423046334646642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#becfa2'
    - '#df8e3d'
    - '#51b3a2'
    - '#ffffff'
    - '#734a5c'
  brandStrength: 0.6868691637646407
  lightness: 0.75
  saturation: 0.36259444104507565
  rhythmicContrast: 0.35080716223455966
purpose: []
