name: CBAA NAD
favicon: null
layout_spectrum: 0.03772660670801997
typography_spectrum: 0.3423046334646642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6868691637646407
  lightness: 0.16430485039018095
  saturation: 0.36259444104507565
  rhythmicContrast: 0.35080716223455966
purpose: []
